apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: ramazancetin/hellonode
  newTag: 2134791b0673762536cf146b862db9e7d0679e20
resources:
- ../base
