apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: ramazancetin/hellonode
  newTag: 72ff39a197301fdb8c042c6ede158ac0e8485f3c
resources:
- ../base
