apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: ramazancetin/hellonode
  newTag: "7"
- name: ramazancetinn/hellonode
  newTag: latest
resources:
- ../base
