apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 4
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: ramazancetin/hellonode:latest
        name: demo
        ports:
        - containerPort: 8080
